salesforce:
  grant_type: "password"
  client_id: "3MVG9dKFWsESbpkHYrOVyyvQaQKn3AMpsaMnJLPMEOYNnIwIRz_Sn02VRuCWRDifJGKLkVMbOtlrIWCsgPyln"
  client_secret: "59A2FA5862B2AE083389DD420FCB2A6CAB68C2937E79DDE0428C1EDDB35AD03A"
  username: "vikas.gupta@fortimize.com.cutx.preprod"
  password: "y9KEsr78HC6>pb%UtRaG0K1X5yPB5GBqR6vG0fw"
  tokenEndpoint: "cutx--preprod.cs47.my.salesforce.com"
